### ISSUE TITLE
Multi-node TODO list

### ISSUE THREAD

**Issue by spirali** [It4innovations/hyperqueue#429]
* [x] Basic functionality
* [x] Multi-node task parking
* [ ] Switch for requesting only workers from the same allocation
* [ ] Dynamic requests of number-of-nodes-per-allocation from auto alloc
* [ ] Priorities
* [ ] Node resource requests for multi-node tasks
* [ ] Time requests for multi-node tasks
* [ ] Debug MPI crash in multi-node tasks on Karolina

**Comment by spirali** [comment]
I forgot to track the progress in this issue. Most of it is done. I will create a new roadmap.
